name: wayforce
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl_phone_field: ^3.1.0
  provider: ^6.0.5
  path_provider: ^2.0.14
  badges: ^3.0.3
  sqflite: ^2.2.6
  permission_handler: ^11.0.0
  toggle_switch: ^2.0.1
  image: ^4.1.4
  flutter_timezone: ^1.0.4
  flutter_screenutil: ^5.7.0
  file_picker: ^8.0.5
  open_file: ^3.3.1
  pinput: ^5.0.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  multiselect_dropdown_flutter: ^0.0.7
  persistent_bottom_nav_bar: ^5.0.2
  http: ^0.13.3
  shared_preferences: ^2.1.1
  dropdown_button2: ^2.0.0
  images_picker: ^1.2.11
  calendar_date_picker2: ^1.1.4
  intl: ^0.19.0
  otp_text_field: ^1.1.3
  fluttertoast: ^8.2.2
  country_picker: ^2.0.20
  top_snackbar_flutter: ^3.0.0+1
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  simple_s3: ^0.3.2
  multi_select_flutter: ^4.1.3
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.5.0
  circular_countdown_timer: ^0.2.3
  flutter_dialogs: ^3.0.0
  #location: ^5.0.3
  geolocator: ^12.0.0
  app_settings: ^5.1.1
  device_info_plus: ^10.1.0
  search_map_place_updated: ^0.0.4
  uuid: ^3.0.7
  quickalert: ^1.0.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  get: ^4.6.6
  # google_places_autocomplete_flutter: ^1.0.6
  # google_place: ^0.4.7
  google_places_flutter: ^2.0.7
  dropdown_search: ^5.0.6
  flutter_typeahead: ^5.0.2
  velocity_x: ^4.1.1
  flutter_spinkit: ^5.2.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  geocoding: ^3.0.0
  firebase_messaging: ^15.0.1
  awesome_notifications: ^0.9.3+1
  firebase_analytics: ^11.0.1
  flutter_local_notifications: ^17.1.2
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  firebase_in_app_messaging: ^0.8.0+1
  flutter_search_bar: ^3.0.0-dev.1
  url_launcher: ^6.2.1
  
  assets_audio_player: ^3.1.1
  # flutter_ringtone_player: ^4.0.0+2

  flutter_ringtone_player:
    git:
      url: https://github.com/KawindaWAD/flutter_ringtone_player.git  
  flutter_html: ^3.0.0-beta.2
  flutter_swipe_button: ^2.1.1+1
  socket_io_client: ^2.0.3+1
  pdf: ^3.10.7
  syncfusion_flutter_pdfviewer: ^20.4.54
   



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/iclogo.png"
  remove_alpha_ios: true
  # min_sdk_android: 21
  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
